import { callAI } from './aiClient.js';

// ── DATASET REWRITER ────────────────────────────────────────────────────────
/**
 * Analyzes a dataset and findings to suggest bias rectifications.
 * @param {Array} dataset    - The raw array of data objects
 * @param {Array} findings   - Findings generated by the module's analysis engine
 * @param {Object} config    - Configuration: { decisionColumn, demographicColumns, proxyColumns }
 * @returns {Object} { originalData, suggestedData, changesExplained }
 */
export function rewriteDataset(dataset, findings, config) {
  const decisionColumn     = (config && config.decisionColumn)     || '';
  const demographicColumns = (config && config.demographicColumns) || [];
  const proxyColumns       = (config && config.proxyColumns)       || [];

  const changesExplained = [];

  // Clone dataset so we don't mutate the original
  const suggestedDataset = dataset.map(row => Object.assign({}, row));

  // 1. Redact demographic columns
  if (demographicColumns.length > 0) {
    changesExplained.push({
      action: 'Anonymization',
      target: demographicColumns.join(', '),
      reason: 'Demographic attributes should not be visible during human review to prevent unconscious bias.',
    });
    suggestedDataset.forEach(row => {
      demographicColumns.forEach(col => {
        if (row[col] !== undefined) row[col] = '[REDACTED]';
      });
    });
  }

  // 2. Redact known proxy variables (e.g. zip code, university)
  if (proxyColumns.length > 0) {
    changesExplained.push({
      action: 'Proxy Variable Masking',
      target: proxyColumns.join(', '),
      reason: 'These fields strongly correlate with protected attributes and risk indirect discrimination.',
    });
    suggestedDataset.forEach(row => {
      proxyColumns.forEach(col => {
        if (row[col] !== undefined) row[col] = '[MASKED]';
      });
    });
  }

  // 3. Threshold adjustment for decision disparate impact based on fairness findings
  (findings || []).forEach(finding => {
    if (finding.severity === 'HIGH' && finding.metric === 'Disparate Impact Ratio') {
      const attribute = finding.attribute || 'the affected group';
      changesExplained.push({
        action: 'Threshold Adjustment / Process Review',
        target: attribute,
        reason: 'Disparate impact ratio is below the 0.80 legal threshold for ' + attribute + '. Re-evaluate the scoring rubric and lower the approval threshold for affected groups until reaching parity.',
      });
    }
  });

  return {
    originalData: dataset,
    suggestedData: suggestedDataset,
    changesExplained
  };
}

// ── TEXT REWRITER ──────────────────────────────────────────────────────────
function sanitizeJSON(rawText) {
  let text = rawText.replace(/^```json\s*/i, '').replace(/```\s*$/i, '');
  const start = text.indexOf('{');
  const end   = text.lastIndexOf('}');
  if (start !== -1 && end !== -1) return text.substring(start, end + 1);
  return text;
}

/**
 * Uses the multi-model AI pipeline to rewrite text to be bias-neutral.
 * @param {string} text - The original text (resume, review, document)
 * @returns {Promise<Object>} The parsed JSON with changesApplied and the rewritten text.
 */
export async function rewriteText(text) {
  const prompt = 'You are a bias-neutral writing expert. Rewrite the following text to remove all signals that could trigger unconscious bias in human reviewers or AI screening systems. Remove or neutralize: names, pronouns, graduation years, addresses, university names, religious references, disability mentions, and any other demographic identifiers. Preserve all qualification content exactly.\n\nReturn JSON only — no preamble, no markdown fences:\n{\n  "rewrittenText": "string",\n  "changesApplied": [{"original": "string", "replacement": "string", "reason": "string"}],\n  "fieldsRedacted": ["string"],\n  "biasSignalsRemoved": "number"\n}\n\nORIGINAL TEXT:\n"""\n' + text.slice(0, 4000) + '\n"""';

  try {
    const { text: resultText, source } = await callAI(prompt);
    console.log('BiasRewriter via ' + source);

    const cleanJSON = sanitizeJSON(resultText);
    const parsed    = JSON.parse(cleanJSON);

    return {
      rewrittenText:      parsed.rewrittenText      || text,
      changesApplied:     parsed.changesApplied     || [],
      fieldsRedacted:     parsed.fieldsRedacted     || [],
      biasSignalsRemoved: parsed.biasSignalsRemoved || 0,
      source
    };
  } catch (err) {
    console.error('BiasRewriter failed to parse AI JSON:', err);
    throw new Error('Failed to compute a bias-neutral rewrite. Please try again.');
  }
}
